/******************************************************************************  
 * Programa ....: Funcoes_Sql.prg  
 * Autor .......: Fulano da Silva  
 * Sintese .....: Conexão com Banco  
 * Data ........: 25/08/2023 às 14:12:29  
 * Revisado em .: 25/08/2023 às 14:12:29  
 ******************************************************************************/  
#include 'agenda.ch'  
  
MemVar oSql

********************************************************************************
FUNCTION CONECTAR_SQL(cHost, nPorta, cPass, cUsr, NomeBanco)
********************************************************************************
LOCAL nError, lConectou := .F., cLocalBanco := "", lCriaTabela := .F.

cServer     := cHost + "/" + alltrim(str(nPorta)) + ":" + NomeBanco && String de conexão
cLocalBanco := vpUserDir + "\" + NomeBanco        && Diretório do banco

IF (lower(ALLTRIM(cHost))=='localhost' .or. ALLTRIM(cHost)=='127.0.0.1') .and.;
   !FILE( cLocalBanco + ".FDB" )

	if file(vpUserDir+'\instsvc.exe')
		cComando := 'instsvc.exe stop'
		Try
			MyRun( cComando )
	      inkey(1)
		   cComando := 'instsvc.exe start'
			MyRun( cComando )
	      inkey(1)
     Catch
     End
	endif

   && Cria o Banco de Dados FireBird
	nRetorno    := FBCreateDB(cLocalBanco + ".FDB", cUsr, cPass, 16384, 'WIN1252', 3 )
   lCriaTabela := .T.
	
	IF nRetorno != 1
      Msginfo("Falha na criação do banco","Atenção")
      quit
   ENDIF

ENDIF

if file(vpUserDir+'\instsvc.exe')
	cComando := 'instsvc.exe stop'
	Try
		MyRun( cComando )
      inkey(1)
	   cComando := 'instsvc.exe start'
		MyRun( cComando )
      inkey(1)
  Catch
  End
endif

&& Conecta no Banco de Dados FireBird
oSql := TFBServer():New(cServer, cUsr, cPass, 3)

if oSql:NetErr()
   Msginfo('Falha na conexão, favor verificar o serviço do FireBird!'+LF+LF+;
	        oSql:Errormsg(),"Atenção")
	quit
endif

if lCriaTabela
   CRIA_TABELAS() && Cria as Tabelas no Banco de Dados
endif

RETURN (.T.)

********************************************************************************
FUNCTION CRIA_TABELAS()  && Criação de Tabelas
********************************************************************************
Local vSql := ''

&& Monta o Scrypt SQL
vSql += "CREATE TABLE CONTATOS (" + LF
vSql += "    ID INTEGER GENERATED BY DEFAULT AS IDENTITY," + LF
vSql += "    NOME VARCHAR(50) DEFAULT ''," + LF
vSql += "    TELEFONE VARCHAR(14) DEFAULT '')" + LF

oSql:StartTransaction() && Abre uma transação dentro do banco
oSql:Execute( vSql )    && Executa o Scrypt SQL

if oSql:NetErr()        && Verifica se deu erro
	Msginfo("Falha na Criação da tabela","Atenção")
   oSql:Rollback()      && Descarta a alteração no banco
else
   oSql:Commit()        && Comita a alteração no banco
endif

Return .T.

